server:
  port: 8888
 
#create avalue to dynamis the context path on url  
app:
  api-prefix: /api/v1 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
          - Path=${app.api-prefix}/identity/**
          filters:
          - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
          - Path=${app.api-prefix}/profile/users/**
          # Path=${app.api-prefix}/profile/users/**, ${app.api-prefix}/profile/internal/users/**
          filters:
          - StripPrefix=2  
          #id: identity_service (id of microservice)
          #uri: http://localhost:8080 (domain and port of microservice)
          #predicates:
          #- Path=${app.api-prefix}/identity/** (liet ke cac api  se nhan dieu huong tu cong 8888, dau phay "," se phan cach cac api )
          #filters:
          #- StripPrefix=2 (loai bo 2 path content "/path1/path2" cua cong 8888 va so sanh gia tri nhan duoc voi api cua microservice)
